apiVersion: v1
kind: ServiceAccount
metadata:
  name: discount-service
automountServiceAccountToken: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discount-service
  labels:
    svc: discount
    app: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: discount
      app: blue
  template:
    metadata:
      labels:
        svc: discount
        app: blue
    spec:
      serviceAccount: discount-service
      containers:
      - name: discount-service
        image: phenrigomes/blue-discount:0.1
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: discount-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: discount-service
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    svc: discount
    app: blue
